<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="abhi-IdeaPad-5-15ITL05" failures="2" tests="10" name="com.guvi.SeleniumTestNgExps.PlayWithConfigs_Tests" time="0.017" errors="0" timestamp="2023-05-15T20:17:20 IST" skipped="0">
  <testcase classname="com.guvi.SeleniumTestNgExps.PlayWithConfigs_Tests" name="checkBinaryStringNull_test10" time="0.001"/>
  <system-out/>
  <testcase classname="com.guvi.SeleniumTestNgExps.PlayWithConfigs_Tests" name="checkLogIn_test2" time="0.001"/>
  <system-out/>
  <testcase classname="com.guvi.SeleniumTestNgExps.PlayWithConfigs_Tests" name="checkLogIn_test3" time="0.001"/>
  <system-out/>
  <testcase classname="com.guvi.SeleniumTestNgExps.PlayWithConfigs_Tests" name="checkMaxNum_test5" time="0.001"/>
  <system-out/>
  <testcase classname="com.guvi.SeleniumTestNgExps.PlayWithConfigs_Tests" name="checkOddNumbers_test9" time="0.001"/>
  <system-out/>
  <testcase classname="com.guvi.SeleniumTestNgExps.PlayWithConfigs_Tests" name="checkLogIn_test1" time="0.004"/>
  <system-out/>
  <testcase classname="com.guvi.SeleniumTestNgExps.PlayWithConfigs_Tests" name="checkArraysMaxItem_test7" time="0.001"/>
  <system-out/>
  <testcase classname="com.guvi.SeleniumTestNgExps.PlayWithConfigs_Tests" name="checkEvenNumbers_test8" time="0.000"/>
  <system-out/>
  <testcase classname="com.guvi.SeleniumTestNgExps.PlayWithConfigs_Tests" name="checkArraysMaxItem_test6" time="0.006">
    <failure message="expected [434] but found [60]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [434] but found [60]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.guvi.SeleniumTestNgExps.PlayWithConfigs_Tests.checkArraysMaxItem_test6(PlayWithConfigs_Tests.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkArraysMaxItem_test6 -->
  <system-out/>
  <testcase classname="com.guvi.SeleniumTestNgExps.PlayWithConfigs_Tests" name="checkMaxNum_test4" time="0.001">
    <failure message="expected [60] but found [30]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [60] but found [30]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.guvi.SeleniumTestNgExps.PlayWithConfigs_Tests.checkMaxNum_test4(PlayWithConfigs_Tests.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkMaxNum_test4 -->
  <system-out/>
</testsuite> <!-- com.guvi.SeleniumTestNgExps.PlayWithConfigs_Tests -->
